import React from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, ArrowRight, BrainCircuit, BriefcaseBusiness, Check, ChevronRight, Code2, Compass, GraduationCap, Palette, Rocket, Sparkles, Users } from 'lucide-react';

const schools = [
  { number: '01', title: 'School of Technology', strapline: 'Build. Design. Analyze. Innovate.', icon: Code2, accent: 'text-cyan-400', courses: ['Product Management', 'UI/UX Design', 'Data Analytics', 'Web Development', 'AI & Automation'] },
  { number: '02', title: 'School of Business', strapline: 'Start. Sell. Scale. Grow.', icon: BriefcaseBusiness, accent: 'text-amber-400', courses: ['Entrepreneurship', 'Digital Marketing', 'Sales & Business Development', 'Business Growth & Strategy', 'AI for Business'] },
  { number: '03', title: 'School of Creative Arts', strapline: 'Create. Communicate. Inspire.', icon: Palette, accent: 'text-fuchsia-400', courses: ['Graphic Design', 'Brand Identity', 'Content Creation', 'Video Editing', 'AI for Creators'] },
  { number: '04', title: 'School of Career & Professional Development', strapline: 'Prepare. Position. Progress.', icon: Compass, accent: 'text-emerald-400', courses: ['Career Launchpad', 'Remote Work & Freelancing', 'Personal Branding', 'AI for Professionals', 'Leadership & Workplace Excellence'] },
];

const programmes = [
  { name: 'AI Professional', duration: '4 Weeks', price: 'N50,000', label: 'Future-ready skills' },
  { name: 'Digital Career Programme', duration: '12 Weeks', price: 'N100,000–N150,000', label: 'A career with momentum' },
  { name: 'Business Builder', duration: '8 Weeks', price: 'N100,000', label: 'From idea to traction' },
  { name: 'Creator Programme', duration: '8 Weeks', price: 'N85,000', label: 'Make work people notice' },
  { name: 'Career Launchpad', duration: '6 Weeks', price: 'N60,000', label: 'Your next move starts here' },
];

const learningSteps = [
  ['LEARN', 'Acquire practical, industry-relevant knowledge.'],
  ['BUILD', 'Apply your knowledge through real-world projects.'],
  ['SHOW', 'Build a portfolio that demonstrates what you can do.'],
  ['GROW', 'Develop your career, business or professional opportunities.'],
];

const Academy = () => {
  const navigateTo = (path) => {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
  };

  const courseSlug = (name) => name.toLowerCase().replace(/&/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#020617] font-sans text-white selection:bg-cyan-500/30 selection:text-cyan-100">
      <div className="fixed inset-0 -z-10 overflow-hidden"><div className="absolute left-[-15%] top-[-10%] h-[55%] w-[55%] rounded-full bg-cyan-950/30 blur-[160px]" /><div className="absolute bottom-[-15%] right-[-10%] h-[50%] w-[50%] rounded-full bg-amber-950/20 blur-[160px]" /></div>
      <nav className="fixed left-0 right-0 top-0 z-50 border-b border-white/5 bg-[#020617]/75 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6"><button onClick={() => navigateTo('/')} className="flex items-center gap-3 text-left"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-500"><Rocket className="h-5 w-5" /></span><span className="font-black uppercase tracking-tighter">Elion</span></button><div className="hidden items-center gap-8 md:flex"><button onClick={() => navigateTo('/')} className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 transition-colors hover:text-white">Solutions</button><span className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-400">Academy</span><button onClick={() => navigateTo('/login')} className="rounded-full bg-white px-5 py-2 text-[10px] font-black uppercase tracking-widest text-slate-950 transition-colors hover:bg-cyan-400">Join cohort</button></div><button onClick={() => navigateTo('/')} className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-slate-400 hover:text-cyan-400 md:hidden"><ArrowLeft className="h-4 w-4" /> Back</button></div></nav>

      <main>
        <section className="mx-auto max-w-7xl px-6 pb-28 pt-40 md:pb-40 md:pt-52"><div className="grid items-end gap-16 lg:grid-cols-[1.05fr_0.95fr]"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} className="space-y-8"><div className="flex items-center gap-3 text-cyan-400"><GraduationCap className="h-6 w-6" /><span className="text-[10px] font-black uppercase tracking-[0.35em]">Elion Academy</span></div><h1 className="max-w-5xl text-6xl font-black uppercase leading-[0.88] tracking-tighter md:text-9xl">Skills.<br /><span className="text-cyan-400">Careers.</span><br />Business. Growth.</h1><p className="max-w-2xl text-lg font-medium leading-relaxed text-slate-300 md:text-xl">Learn something useful, make it real, and let the work open a door.</p><div className="flex flex-wrap gap-4"><a href="#programmes" className="group inline-flex items-center gap-3 rounded-2xl bg-cyan-500 px-7 py-4 text-xs font-black uppercase tracking-widest shadow-2xl shadow-cyan-500/20 transition-all hover:bg-cyan-400">Find your programme <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" /></a><button onClick={() => navigateTo('/signup')} className="inline-flex items-center gap-3 rounded-2xl border border-white/15 bg-white/5 px-7 py-4 text-xs font-black uppercase tracking-widest transition-all hover:bg-white hover:text-slate-950">Meet the next cohort</button></div></motion.div><motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.9, delay: 0.15 }} className="relative overflow-hidden rounded-[2.5rem] border border-white/10 bg-white/5"><img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=85" alt="Learners working together around a table" className="human-image h-[390px] w-full object-cover opacity-80" referrerPolicy="no-referrer" /><div className="absolute inset-0 bg-gradient-to-t from-[#020617] via-[#020617]/20 to-transparent" /><div className="absolute inset-x-8 bottom-8 md:inset-x-12"><div className="mb-4 flex items-center gap-3 text-cyan-400"><Sparkles className="h-6 w-6" /><span className="text-[10px] font-black uppercase tracking-[0.3em]">The Elion ecosystem</span></div><div className="space-y-2 text-3xl font-black uppercase leading-tight tracking-tighter md:text-5xl">We build businesses.<br />We build technology.<br />We build brands.<br /><span className="text-cyan-400">And we build people.</span></div></div></motion.div></div></section>

        <section className="border-y border-white/5 bg-white/[0.03] py-24 md:py-32"><div className="mx-auto max-w-7xl px-6"><div className="mb-14 max-w-2xl space-y-4"><p className="text-[10px] font-black uppercase tracking-[0.3em] text-cyan-400">Four paths. One launchpad.</p><h2 className="text-5xl font-black uppercase leading-none tracking-tighter md:text-7xl">Find your school.</h2><p className="text-lg font-medium leading-relaxed text-slate-400">Choose a direction, learn from practitioners and leave with work that moves you forward.</p></div><div className="grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 md:grid-cols-2">{schools.map(({ number, title, strapline, icon: Icon, accent, courses }, index) => <motion.article key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className="group bg-[#071126] p-8 transition-colors hover:bg-[#0b1a35] md:p-10"><div className="mb-12 flex items-start justify-between"><span className={`text-4xl font-black tracking-tighter ${accent}`}>{number}</span><Icon className={`h-7 w-7 ${accent}`} /></div><h3 className="max-w-sm text-3xl font-black uppercase leading-none tracking-tighter">{title}</h3><p className={`mt-4 text-sm font-black uppercase tracking-widest ${accent}`}>{strapline}</p><ul className="mt-8 space-y-3 border-t border-white/10 pt-6">{courses.map(course => <li key={course}><button onClick={() => navigateTo(`/academy/course/${courseSlug(course)}`)} className="flex w-full items-center gap-3 text-left text-sm font-medium text-slate-400 transition-colors hover:text-white"><Check className={`h-4 w-4 ${accent}`} />{course}<ChevronRight className="ml-auto h-4 w-4 opacity-0 transition-opacity group-hover:opacity-100" /></button></li>)}</ul><button onClick={() => document.getElementById('programmes')?.scrollIntoView({ behavior: 'smooth' })} className="mt-10 flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-white transition-colors group-hover:text-cyan-400">See programme paths <ChevronRight className="h-4 w-4" /></button></motion.article>)}</div></div></section>

        <section className="mx-auto max-w-7xl px-6 py-24 md:py-36"><div className="grid items-center gap-16 lg:grid-cols-[0.8fr_1.2fr]"><div><div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-cyan-500/15 text-cyan-400"><BrainCircuit className="h-8 w-8" /></div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-cyan-400">The Academy differentiator</p><h2 className="mt-5 text-5xl font-black uppercase leading-[0.92] tracking-tighter md:text-7xl">AI isn't the future of one industry.<br /><span className="text-cyan-400">It's the future of work.</span></h2></div><div className="grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 sm:grid-cols-2">{['AI for Business', 'AI for Professionals', 'AI for Creators', 'AI for Developers', 'AI for Entrepreneurs'].map((item, index) => <div key={item} className="bg-white/5 p-6 text-sm font-black uppercase tracking-tight text-slate-200 transition-colors hover:bg-cyan-500 hover:text-slate-950"><span className="mb-8 block text-[10px] text-cyan-400">0{index + 1}</span>{item}</div>)}</div></div></section>

        <section className="bg-cyan-500 py-24 text-slate-950 md:py-32"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-16 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-800">How we learn</p><h2 className="mt-5 text-6xl font-black uppercase leading-[0.88] tracking-tighter md:text-8xl">Don't just learn a skill.<br /><span className="text-white">Build something with it.</span></h2></div><div className="grid gap-8 sm:grid-cols-2">{learningSteps.map(([title, text], index) => <div key={title} className="border-t border-slate-950/20 pt-5"><div className="mb-5 flex items-center justify-between"><span className="text-xs font-black tracking-widest">{title}</span><span className="font-mono text-xs">0{index + 1}</span></div><p className="max-w-xs text-sm font-bold leading-relaxed text-slate-800">{text}</p></div>)}</div></div></div></section>

        <section id="programmes" className="mx-auto max-w-7xl px-6 py-24 md:py-36"><div className="mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-cyan-400">Start with a focused sprint</p><h2 className="mt-4 text-5xl font-black uppercase leading-none tracking-tighter md:text-7xl">Featured programmes</h2></div><button onClick={() => navigateTo('/signup')} className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-cyan-400 hover:text-white">View all programmes <ArrowRight className="h-4 w-4" /></button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{programmes.map((programme, index) => <button key={programme.name} onClick={() => navigateTo(`/academy/course/${courseSlug(programme.name)}`)} className={`flex flex-col justify-between border border-white/10 bg-white/5 p-6 text-left transition-all hover:-translate-y-1 hover:border-cyan-400/50 ${index === 0 ? 'border-cyan-400/40 bg-cyan-500/10' : ''}`}><div><div className="mb-12 flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-widest text-cyan-400">0{index + 1}</span><Users className="h-4 w-4 text-slate-500" /></div><h3 className="text-2xl font-black uppercase leading-none tracking-tighter">{programme.name}</h3><p className="mt-3 text-sm font-medium text-slate-400">{programme.label}</p></div><div className="mt-12 border-t border-white/10 pt-4"><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">{programme.duration}</p><p className="mt-2 text-xl font-black text-white">{programme.price}</p><span className="mt-4 flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-cyan-400">View course <ArrowRight className="h-4 w-4" /></span></div></button>)}</div></section>

        <section className="mx-6 mb-24 overflow-hidden rounded-[2.5rem] border border-white/10 bg-white/5 md:mx-auto md:max-w-7xl"><div className="flex flex-col items-start justify-between gap-10 p-8 md:flex-row md:items-end md:p-16"><div className="max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[0.3em] text-cyan-400">Built for momentum</p><h2 className="mt-5 text-5xl font-black uppercase leading-[0.9] tracking-tighter md:text-8xl">Your next chapter starts here.</h2></div><button onClick={() => navigateTo('/signup')} className="group flex shrink-0 items-center gap-3 rounded-2xl bg-white px-7 py-4 text-xs font-black uppercase tracking-widest text-slate-950 transition-colors hover:bg-cyan-400">Join the next cohort <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" /></button></div></section>
      </main>
      <footer className="border-t border-white/5 py-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-6 text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 md:flex-row"><span>Elion Academy / Part of Elion</span><span>Skills. Careers. Business. Growth.</span></div></footer>
    </div>
  );
};

export default Academy;